#!/usr/bin/bash

#file --mime-type "$1" | cut -d ":" -f 2 | cut -d "/" -f 1 | cut -d " " -f 2

#echo

tipo=$(file --mime-type "$1" | cut -d ":" -f 2 | cut -d " " -f 2)

case "$tipo" in

  "application/zip")
    echo "Archivo comprimido, ¿descomprimir aquí? S/N"
    read respuesta
    if [ $respuesta = "S" ] || [ $respuesta = "s" ]
    then
    	unzip "$1"
    fi
    ;;

  "application/gzip")
    echo "Archivo comprimido, ¿descomprimir aquí? S/N"
    read respuesta
    if [ $respuesta = "S" ] || [ $respuesta = "s" ]
    then
    	tar xvf "$1"
    fi
    ;;

  "application/x-tar")
    echo "Archivo comprimido, ¿descomprimir aquí? S/N"
    read respuesta
    if [ $respuesta = "S" ] || [ $respuesta = "s" ]
    then
    	tar xvf "$1"
    fi
    ;;

  "application/x-xz")
    echo "Archivo comprimido, ¿descomprimir aquí? S/N"
    read respuesta
    if [ $respuesta = "S" ] || [ $respuesta = "s" ]
    then
    	tar -Jxvf "$1"
    fi
    ;;

  "inode/directory")
    cd "$1"
    ;;

  "image/svg+xml")
    ristretto "$1" &
    ;;

  "application/pdf")
    evince "$1" &
    ;;

  "image/jpeg")
    ristretto "$1" &
    ;;

  "image/png")
    ristretto "$1" &
    ;;

  "image/x-xcf")
    gimp "$1" &
    ;;

  "image/svg+xml")
    inkscape "$1" &
    ;;

  "text/plain")
    typora "$1" &
    ;;
  *)
    echo "Tipo de archivo no incluido aun"
    ;;

esac

