#!/usr/bin/bash

#file --mime-type "$1" | cut -d ":" -f 2 | cut -d "/" -f 1 | cut -d " " -f 2

#echo

tipo=$(file --mime-type "$1" | cut -d ":" -f 2 | cut -d " " -f 2)

case "$tipo" in

  "application/pdf")
    evince "$1" &
    ;;

  "image/jpeg")
    ristretto "$1" &
    ;;

  "text/plain")
    typora "$1" &
    ;;
  *)
    echo "Tipo de archivo no incluido aun"
    ;;

esac

